title: RBB Marketing
description: Your source for premium promotional products and employee recognition solutions
url: http://localhost:4000
baseurl: ""
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site customization
colors:
  primary: "#402195"
  secondary: "#b45e37"
  dark: "#333333"

# Contact Information
contact:
  email: info@rbbmarketing.com
  phone: (987) 654-3210
  address: 456 Sample Road, Example Town, EX 67890 